# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - gem update --system
      - gem install bundle
      - bundle install
      - bundle exec jekyll build
      - bundle exec jekyll serve --livereload
